# Generated by Django 4.2.6 on 2023-10-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(help_text="Отдел кратко", max_length=50),
                ),
                ("name", models.CharField(help_text="Название отдела", max_length=255)),
                (
                    "additional_info",
                    models.CharField(
                        help_text="Дополнительная информация по отделу", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Рассылка", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("+", "Включена"),
                            ("-", "Отключена"),
                            ("X", "Неактивна"),
                        ],
                        default="+",
                        max_length=1,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("D", "1 раз в день"),
                            ("DD", "Несколько раз в день"),
                            ("W", "1 раз в неделю"),
                            ("O", "Однократно"),
                        ],
                        default="D",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое название должности",
                        max_length=50,
                        verbose_name="Должность кратко",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Должность", max_length=255, verbose_name="Должность"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("system_name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("+", "Работает"),
                            ("-", "Уволен"),
                            ("X", "Удалить из рассылки"),
                        ],
                        default="+",
                        max_length=1,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("М", "Мужчина"),
                            ("Ж", "Женщина"),
                            ("-", "Не указано"),
                        ],
                        default="М",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField(null=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emaillist.department",
                    ),
                ),
                (
                    "subscription",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите подписки",
                        to="emaillist.subscription",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emaillist.title",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "department",
                    "status",
                    "title",
                    "last_name",
                    "first_name",
                ],
            },
        ),
    ]
