# Generated by Django 4.2.6 on 2023-10-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="additional_info",
            field=models.CharField(
                help_text="Дополнительная информация по отделу",
                max_length=255,
                verbose_name="Доп информация",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Название отдела", max_length=255, verbose_name="Отдел"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="short_name",
            field=models.CharField(
                help_text="Отдел кратко", max_length=50, verbose_name="Отдел кратко"
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="birthday",
            field=models.DateField(null=True, verbose_name="День рождения"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emaillist.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужчина"), ("Ж", "Женщина"), ("-", "Не указано")],
                default="М",
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Отчетство"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="status",
            field=models.CharField(
                choices=[
                    ("+", "Работает"),
                    ("-", "Уволен"),
                    ("X", "Удалить из рассылки"),
                ],
                default="+",
                max_length=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="subscription",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите подписки",
                to="emaillist.subscription",
                verbose_name="Подписки",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="system_name",
            field=models.CharField(max_length=50, verbose_name="Название в системе"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emaillist.title",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("D", "1 раз в день"),
                    ("DD", "Несколько раз в день"),
                    ("W", "1 раз в неделю"),
                    ("O", "Однократно"),
                ],
                default="D",
                max_length=2,
                verbose_name="Частота",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                help_text="Рассылка", max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("+", "Включена"), ("-", "Отключена"), ("X", "Неактивна")],
                default="+",
                max_length=1,
                verbose_name="Статус",
            ),
        ),
    ]
