# Generated by Django 4.2.6 on 2023-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0003_alter_department_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="День рождения"),
        ),
    ]
