"""add todolist

Revision ID: 98d9b5ef87f1
Revises: 5c03c16ecc42
Create Date: 2023-12-09 14:29:49.399692

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98d9b5ef87f1'
down_revision = '5c03c16ecc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('todo', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_list')
    # ### end Alembic commands ###
