# Generated by Django 4.2.6 on 2023-10-22 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0005_workinguser_subscription_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="created_by",
        ),
    ]
