# Generated by Django 4.2.6 on 2023-10-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0006_remove_subscription_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emaillist.workinguser",
            ),
        ),
    ]
