FROM python:3.11.4-bullseye

WORKDIR /app

RUN pip install --upgrade pip "poetry==1.5.1"
RUN poetry config virtualenvs.create false --local

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-ansi --only main

# lint
RUN pip install --upgrade pip
RUN pip install flake8==6.0.0
COPY . .
RUN flake8 --ignore=E501,F401 .

RUN chmod +x ./prestart-dev.sh
ENTRYPOINT ["./prestart-dev.sh"]
CMD ["python", "app.py"]
