name: Django CI 

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        echo first installation complete
        cd ./homework_09
        echo $PATH
        echo TEST---------------------
        poetry install
        echo poetry install DONE
        cd /nomad
        python ./homework_09/nomad/manage.py runserver
    - name: Run Tests
      run: |
        python manage.py test
